name: Continuous integration
on: [ push, pull_request ]

jobs:
    test:
        name: Test - PHP ${{matrix.php-version}} - OS ${{matrix.os}} - Dependencies ${{matrix.dependencies}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: false
            matrix:
                php-version: [ '8.0' ]
                os: [ ubuntu-latest, windows-latest, macos-latest ]
                dependencies: [ lowest, highest ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
            -   name: Install dependencies (lowest)
                if: matrix.dependencies == 'lowest'
                run: composer update --prefer-lowest
            -   name: Install dependencies (highest)
                if: matrix.dependencies == 'highest'
                run: composer update
            -   name: Setup problem matchers for PHP
                run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
            -   name: Setup problem matchers for PHPUnit
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            -   name: Run tests
                run: vendor/bin/phpunit

    lint:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
            -   name: Install dependencies
                run: composer update
            -   name: Lint
                run: vendor/bin/phpcs
            -   name: Static analysis
                run: vendor/bin/psalm
